### ISSUE TITLE
Use imgix to handle image

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/devfest2018#106]

**Comment by jlandure** [comment]
Avant : 
<img width="790" alt="capture d ecran 2018-05-22 a 14 39 40" src="https://user-images.githubusercontent.com/525974/40362940-4b2105e6-5dce-11e8-8747-9025cc51da52.png">

Après : 
<img width="784" alt="capture d ecran 2018-05-22 a 14 40 47" src="https://user-images.githubusercontent.com/525974/40362950-4fd5a3bc-5dce-11e8-88ef-bd28efbd9cac.png">

**Comment by xavmarc** [comment]
Sans imgix
![image](https://user-images.githubusercontent.com/5824142/40362980-676786ee-5dce-11e8-89fd-1bd94645cc0e.png)

Avec imgix
![image 1](https://user-images.githubusercontent.com/5824142/40362985-6c60c6ec-5dce-11e8-97a6-aaa36c4a1e7b.png)

**Comment by xavmarc** [comment]
Sans imgix
![image](https://user-images.githubusercontent.com/5824142/40363240-452a124e-5dcf-11e8-8b09-fa59697984b1.png)

Avec imgix
![image](https://user-images.githubusercontent.com/5824142/40363269-59faac4c-5dcf-11e8-98c7-ad89fbde8437.png)

**Comment by jlandure** [comment]
Marrant on a pas les mêmes résultats 🤔 
<img width="731" alt="capture d ecran 2018-05-22 a 21 07 19" src="https://user-images.githubusercontent.com/525974/40384561-2db50454-5e04-11e8-804e-294b583b831d.png">

**Comment by xavmarc** [comment]
Marrant oui, mais ça correspond a quelle version tes résultats ? Avec imgix ? Sans imgix ? Autre version ??

**Comment by xavmarc** [comment]
update (on perd en best practices mais on gagne en perf
![image](https://user-images.githubusercontent.com/5824142/40742143-d5baa68c-644d-11e8-8957-d2959d926134.png)

**Comment by jlandure** [comment]
Oué  faudrait quand même pour virer maps... 
<img width="799" alt="capture d ecran 2018-05-30 a 21 11 08" src="https://user-images.githubusercontent.com/525974/40742231-1b465ea8-644e-11e8-88ac-16502e7a66dc.png">

**Comment by jlandure** [comment]
no more need. but keep it mind imgix can help for better performance. Let's try next year.
