### ISSUE TITLE
contenu de la page pratique

### ISSUE THREAD

**Issue by pguyard** [GDG-Nantes/devfest2018#18]
- indiquer comment/où acheter sa place ?
- indication pour les personnes à mobilité réduite
- indiquer les horaires d’ouverture/fermeture

**Comment by xavmarc** [comment]
OK pour les 2 derniers par contre le premier je sais pas si ça vaut le coup de le mettre ??

**Comment by pguyard** [comment]
c'est pour avoir une page pratique la plus exhaustive possible.
