### ISSUE TITLE
Perte de mon planning

### ISSUE THREAD

**Issue by ArtyMaury** [GDG-Nantes/devfest2018#220]
Bonjour, 

Peu après l'annonce des speakers, j'ai rempli mon planning avec de nombreuses conférences qui semblaient intéressantes. Aujourd'hui je ne retrouve plus ces conférences, mon planning a été vidé. Y a-t-il eu perte des données ou puis-je les récupérer?

Merci.

**Comment by jlandure** [comment]
Désolé pour ce désagrément, nous essaierons de changer notre mécanisme de favoris pour la prochaine édition.
