### ISSUE TITLE
tweetledee

### ISSUE THREAD

**Issue by xavmarc** [GDG-Nantes/devfest2018#7]
A voir si on peur reprendre celui de @bpetetot (https://tweetledee.petetot.fr/) ?

**Comment by bpetetot** [comment]
L'année dernière on était sur cette adresse mais @jlandure l'avait mis en place sur Heroku, je pense qu'il fonctionne toujours, il faut juste récupérer la conf qu'on avait l'année dernière.

**Comment by jlandure** [comment]
Faut utiliser le même que l'année dernière si possible 👍 
`https://tweeter-devfestnantes.herokuapp.com/favoritesjson.php?c=10&cache_interval=8000`

**Comment by pguyard** [comment]
@jlandure c'est déjà le cas mais cela ne fonctionne plus ;)
'''Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.'''

**Comment by xavmarc** [comment]
Idem sur le site de 2017 ça ne fonctionne plus

**Comment by jlandure** [comment]
C'est de nouveau up 👍 
cf https://github.com/GDG-Nantes/tweetledee-docker
